Allow to configure S3 credentials
appuio/component-openshift4-registry pull request #4
Opened 2020-11-12 09:56 UTC by corvus-ch

## Checklist

- [ ] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [ ] Update the ./CHANGELOG.md.
- [ ] Link this PR to related issues.

2020-11-12 11:35 UTC, ccremer requested changes

2020-11-12 11:35 UTC, ccremer commented on docs/modules/ROOT/pages/references/parameters.adoc
> +If set, the secret `mage-registry-private-configuration-user`.
```suggestion
If set, the secret `image-registry-private-configuration-user`.
```

2020-11-12 12:39 UTC, srueg requested changes

2020-11-12 12:39 UTC, srueg commented on docs/modules/ROOT/pages/references/parameters.adoc
> +If set, the secret `image-registry-private-configuration-user`.
```suggestion
If set, the secret `image-registry-private-configuration-user` will be created containing the credentials.
```

2020-11-12 12:39 UTC, srueg commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Do this when configuring an S3 type at `config.storage`.
```suggestion
Use this when configuring an S3 type for `config.storage`.
```

2020-11-12 13:02 UTC, ccremer approved these changes

2020-11-13 08:03 UTC, srueg approved these changes

2020-11-13 09:13 UTC, merged